from .auth import build_login_context
from .dashboard import get_panel_context
from .category import get_categories_context, get_create_category_context, get_edit_category_context, get_delete_category_context
from .product import get_products_context, get_create_product_context, get_edit_product_context, get_delete_product_context
from .ad import get_ads_context, get_create_ad_context, get_edit_ad_context, get_delete_ad_context
